##############################################################################
## Discover a machine's power status with IPMI
##############################################################################

- name: Determin machine power state
  command: "/sbin/fence_ipmilan --ip {{ server }} --username {{ username }} --password {{ password }} -o status"
