
##############################################################################
## Power on an machine with IPMI
##############################################################################

- name: Power on machine
  command: "/sbin/fence_ipmilan --ip {{ server }} --username {{ username }} --password {{ password }} -o on"
